### добавить пользователя

POST http://localhost:9999/api/v1/users
Content-Type: application/json

{
  "login":"user4",
  "password": "user1password",
  "role": "ADMIN"
}

### редактировать пользователя

PUT http://localhost:9999/api/v1/users
Content-Type: application/json

{
  "login":"user3",
  "password": "user3password",
  "role": "USER"
}

### запрос токена
GET http://localhost:9999/api/v1/users/token

### добавить магазин

POST http://localhost:9999/api/v1/shops
Content-Type: application/json

{
  "name":"тестовый магазин 1",
  "address":"тестовая улица 1",
  "workingHours":"8 - 20"
}
### редактировать магазин

PUT http://localhost:9999/api/v1/shops
Content-Type: application/json

{
  "id":"2",
  "name":"aaa",
  "workingHours":"10 - 11",
  "lon":"454355",
  "lat":"o8747843"
}

### получить полный список магазинов

GET http://localhost:9999/api/v1/shops

### добавить категорию

POST http://localhost:9999/api/v1/categories
Content-Type: application/json

{
  "name":"химоза"
}

### редактировать категорию

PUT http://localhost:9999/api/v1/categories
Content-Type: application/json

{
  "id":"2",
  "name":"мимоза"
}

### получить полный список категорий

GET http://localhost:9999/api/v1/categories

### добавить продукт 1

POST http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3001",
  "name": "пушка",
  "type": "тепловая",
  "description": "пушка детская",
  "shop_id": "3",
  "category_id": "2",
  "price":
     {
       "sale_price":"4000",
       "factory_price": "3000",
       "discount_price": "0",
       "is_active": "true"
     }
}

### добавить продукт 2

POST http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3002",
  "name": "ручка",
  "type": "дверная",
  "description": "ручка дверная хромированная",
  "shop_id": "1",
  "category_id": "1",
  "price":
  {
    "sale_price":"4000",
    "factory_price": "3000",
    "discount_price": "0",
    "is_active": "true"
  }
}

### добавить продукт 3

POST http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MywiUm9sZSI6IkFETUlOIiwiZXhwIjoxNjMwNjE5NDk4LCJpYXQiOjE2MzA2MTU4OTh9.k4_UM1JL2JsC0f3qvkuA5Q261iyREKbwGEDyqkb17Wm-F1_q0Rb4i98h9wi6tawhUag-jgYo2pP3eoly7Hv8HjW18Bwle4RActTGxWeJdPSRQCGT1YCQ4yNUqUeDxDjjqwXtN4NcrvD5Oh-MO4_wgm97ZhZnzHuGCVybzVIDI7TohGVMN9hQ7QChWF48j0G50HNhnABD4zTB_vR_0q2_NAzGA6Q99SyhQV0p7f3Pn62DblU20b_vbb8ya46IjJi1bynw3DzAl9X-UVsW56MbogcRwS7oU7YlU5ktX21wVLdjIe1e8LFNfpFSru9h5GribCtjOS_bDb5jtG7y4IBAPQ

{
  "sku":"3003",
  "name": "тушка",
  "type": "мясное",
  "description": "тушка тушканчика",
  "shop_id": "2",
  "category_id": "3",
  "price":
  {
    "sale_price":"400",
    "factory_price": "300",
    "discount_price": "10",
    "is_active": "true"
  }
}

### добавить продукт 4

POST http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3004",
  "name": "пушка",
  "type": "тепловая",
  "description": "пушка строительная",
  "shop_id": "4",
  "category_id": "1",
  "price":
  {
    "sale_price":"7000",
    "factory_price": "5000",
    "discount_price": "40",
    "is_active": "true"
  }
}

### добавить продукт 5

POST http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3005",
  "name": "сушка",
  "type": "бельевая",
  "description": "сушка для белья",
  "shop_id": "4",
  "category_id": "5",
  "price":
  {
    "sale_price":"1000",
    "factory_price": "300",
    "discount_price": "15",
    "is_active": "true"
  }
}

### редактировать продукт

PUT http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3003",
  "name": "подушка",
  "price":
  {
    "sale_price":"9000"
  }
}

### получить полный список продуктов
GET http://localhost:9999/api/v1/products

### добавить цену

POST http://localhost:9999/api/v1/prices
Content-Type: application/json

{
  "sale_price":"1000",
  "factory_price": "900",
  "discount_price": "10",
  "is_active": "true",
  "product_id": "21e370aa-f15e-42e8-bd39-b7306e595420"
}

### редактировать цену
PUT http://localhost:9999/api/v1/prices
Content-Type: application/json

{
"id":"40",
"sale_price":"1000",
"factory_price": "900",
"discount_price": "20",
"is_active": "true",
"product_id": "2800d950-5c62-49e2-a705-c74ba77f57d0"
}

### получить полный список цен
GET http://localhost:9999/api/v1/prices

### получить список продуктов по категории
GET http://localhost:9999/api/v1/categories/4/products

### получить продукт по имени
GET http://localhost:9999/api/v1/search/подушка

### получить список активных продуктов магазина
GET http://localhost:9999/api/v1/shops/3/products