
### добавить магазин

POST http://localhost:9999/api/v1/shops
Content-Type: application/json

{
  "name":"тестовый магазин 1",
  "address":"тестовая улица 1",
  "workingHours":"8 - 20"
}
### редактировать магазин

PUT http://localhost:9999/api/v1/shops
Content-Type: application/json

{
  "id":"18",
  "name":"aaa",
  "workingHours":"10 - 11",
  "lon":"454355",
  "lat":"o8747843"
}

### получить полный список магазинов

GET http://localhost:9999/api/v1/shops

### добавить категорию

POST http://localhost:9999/api/v1/categories
Content-Type: application/json

{
  "name":"ватрушки"
}

### редактировать категорию

PUT http://localhost:9999/api/v1/categories
Content-Type: application/json

{
  "id":"12",
  "name":"старушки"
}

### получить полный список категорий

GET http://localhost:9999/api/v1/categories

### добавить продукт

POST http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"3000",
  "name": "ручка",
  "type": "стройматериалы",
  "description": "ручка дверная, хромированная",
  "shop_id": "4",
  "category_id": "9"
}

### редактировать продукт

PUT http://localhost:9999/api/v1/products
Content-Type: application/json

{
  "sku":"2099",
  "name": "dучка",
  "is_active": "true"
}

### добавить цену

POST http://localhost:9999/api/v1/prices
Content-Type: application/json

{
  "sale_price":"50000",
  "factory_price": "10000",
  "discount_price": "0",
  "is_active": "true",
  "product_id": "9349ce04-df0b-11eb-8565-0242ac110002"
}

### редактировать цену
PUT http://localhost:9999/api/v1/prices
Content-Type: application/json

{
"sale_price":"2000",
"factory_price": "2000",
"discount_price": "0",
"is_active": "true",
"product_id": "9349ce04-df0b-11eb-8565-0242ac110002"
}

### получить полный список цен
GET http://localhost:9999/api/v1/prices
