### запрос токена
POST http://localhost:9999/api/v1/auth
Content-Type: application/json

{
  "login": "user2",
  "password": "user1password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received '" + response.contentType.mimeType + "'");
  client.global.set("token", response.body.token);
});
%}


### добавить пользователя

POST http://localhost:9999/api/v1/users
Content-Type: application/json
Authorization: {{token}}

{
  "login":"user7",
  "password": "user1password",
  "role": "USER"
}

### редактировать пользователя

PUT http://localhost:9999/api/v1/users
Content-Type: application/json
Authorization: {{token}}

{
  "login":"user7",
  "password": "user6password"
}

### редактировать роль пользователя

PUT http://localhost:9999/api/v1/users/addrole
#Content-Type: application/json
Authorization: {{token}}

{
  "login":"user7",
  "role": "ADMIN"
}

### добавить магазин

POST http://localhost:9999/api/v1/shops
Content-Type: application/json
Authorization: {{token}}

{
  "name":"тестовый магазин 1",
  "address":"тестовая улица 1",
  "workingHours":"8 - 20"
}
### редактировать магазин

PUT http://localhost:9999/api/v1/shops
Content-Type: application/json
Authorization: {{token}}

{
  "id":"2",
  "name":"aaa",
  "workingHours":"10 - 11",
  "lon":"454355",
  "lat":"o8747843"
}

### получить полный список магазинов

GET http://localhost:9999/api/v1/shops
Authorization: {{token}}

### добавить категорию

POST http://localhost:9999/api/v1/categories
Content-Type: application/json
Authorization: {{token}}

{
  "name":"химоза"
}

### редактировать категорию

PUT http://localhost:9999/api/v1/categories
Content-Type: application/json
Authorization: {{token}}

{
  "id":"2",
  "name":"мимоза"
}

### получить полный список категорий

GET http://localhost:9999/api/v1/categories
Authorization: {{token}}

### добавить продукт 1

POST http://localhost:9999/api/v1/products
Content-Type: application/json
##Authorization: {{token}}

{
  "sku":"3001",
  "name": "пушка",
  "type": "тепловая",
  "description": "пушка детская",
  "shop_id": "3",
  "category_id": "2",
  "price":
     {
       "sale_price":"4000",
       "factory_price": "3000",
       "discount_price": "0",
       "is_active": "true"
     }
}

### добавить продукт 2

POST http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: {{token}}

{
  "sku":"3002",
  "name": "ручка",
  "type": "дверная",
  "description": "ручка дверная хромированная",
  "shop_id": "1",
  "category_id": "1",
  "price":
  {
    "sale_price":"4000",
    "factory_price": "3000",
    "discount_price": "0",
    "is_active": "true"
  }
}

### добавить продукт 3

POST http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: {{token}}

{
  "sku":"3003",
  "name": "тушка",
  "type": "мясное",
  "description": "тушка тушканчика",
  "shop_id": "2",
  "category_id": "3",
  "price":
  {
    "sale_price":"400",
    "factory_price": "300",
    "discount_price": "10",
    "is_active": "true"
  }
}

### добавить продукт 4

POST http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: {{token}}

{
  "sku":"3004",
  "name": "пушка",
  "type": "тепловая",
  "description": "пушка строительная",
  "shop_id": "4",
  "category_id": "1",
  "price":
  {
    "sale_price":"7000",
    "factory_price": "5000",
    "discount_price": "40",
    "is_active": "true"
  }
}

### добавить продукт 5

POST http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: {{token}}

{
  "sku":"3005",
  "name": "сушка",
  "type": "бельевая",
  "description": "сушка для белья",
  "shop_id": "4",
  "category_id": "5",
  "price":
  {
    "sale_price":"1000",
    "factory_price": "300",
    "discount_price": "15",
    "is_active": "true"
  }
}

### редактировать продукт

PUT http://localhost:9999/api/v1/products
Content-Type: application/json
Authorization: {{token}}

{
  "sku":"3003",
  "name": "подушка",
  "is_active": "false",
  "price":
  {
    "sale_price":"9000"
  }
}

### получить полный список продуктов
GET http://localhost:9999/api/v1/products
Authorization: {{token}}

### редактировать цену
PUT http://localhost:9999/api/v1/prices
Content-Type: application/json
Authorization: {{token}}

{
"id":"4",
"sale_price":"1000",
"factory_price": "900",
"discount_price": "20",
"is_active": "true",
"product_id": "2800d950-5c62-49e2-a705-c74ba77f57d0"
}

### получить полный список цен
GET http://localhost:9999/api/v1/prices
Authorization: {{token}}

### получить список продуктов по категории
GET http://localhost:9999/api/v1/categories/1/products
Authorization: {{token}}

### получить продукт по имени
GET http://localhost:9999/api/v1/search/подушка
Authorization: {{token}}

### получить список активных продуктов магазина
GET http://localhost:9999/api/v1/shops/4/products
Authorization: {{token}}